apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeblocks-docs.fullname" . }}
  labels:
    {{- include "kubeblocks-docs.labels" . | nindent 4 }}
type: Opaque
data:
  FEISHU_WEBHOOK: {{ .Values.env.FEISHU_WEBHOOK | b64enc | quote }}